# Generated by Django 2.2.5 on 2019-09-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='bikes/'),
        ),
    ]
