# Generated by Django 2.2.5 on 2019-09-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_auto_20190905_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/')),
            ],
        ),
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='icon',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/brands/'),
        ),
        migrations.AddField(
            model_name='bike',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='bikes', to='bikes.Image'),
        ),
    ]
