# Generated by Django 2.2.5 on 2019-09-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_auto_20190906_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
    ]
