# Generated by Django 2.2.5 on 2019-09-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_auto_20190907_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image0',
        ),
        migrations.AddField(
            model_name='image',
            name='image1',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image10',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image11',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image12',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image13',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image14',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image15',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image4',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image5',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image6',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image7',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image8',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='image',
            name='image9',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
    ]
