# Generated by Django 2.2.5 on 2019-09-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_auto_20190907_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='images',
        ),
        migrations.AddField(
            model_name='bike',
            name='image0',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image1',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image10',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image11',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image12',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image13',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image14',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image15',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image4',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image5',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image6',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image7',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image8',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image9',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/bikes/rotation'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
