# Generated by Django 2.2.5 on 2019-09-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_auto_20190907_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displacement', models.CharField(max_length=20)),
                ('compressionRatio', models.CharField(max_length=20)),
                ('bore', models.CharField(max_length=20)),
                ('stroke', models.CharField(max_length=20)),
                ('length', models.CharField(max_length=20)),
                ('wheelbase', models.CharField(max_length=20)),
                ('clearance', models.CharField(max_length=20)),
                ('trail', models.CharField(max_length=20)),
                ('dryweight', models.CharField(max_length=20)),
                ('fueltank', models.CharField(max_length=20)),
                ('torque', models.CharField(max_length=20)),
                ('torquerpm', models.CharField(max_length=20)),
                ('horsepower', models.CharField(max_length=20)),
                ('fuelconsumption', models.CharField(max_length=20)),
                ('co2emissions', models.CharField(max_length=20)),
                ('primarydrive', models.CharField(max_length=20)),
                ('firstgear', models.CharField(max_length=20)),
                ('secondgear', models.CharField(max_length=20)),
                ('thirdgear', models.CharField(max_length=20)),
                ('fourthgear', models.CharField(max_length=20)),
                ('fifthgear', models.CharField(max_length=20)),
                ('sixthgear', models.CharField(max_length=20)),
                ('frontbrakes', models.CharField(max_length=20)),
                ('rearbrakes', models.CharField(max_length=20)),
                ('frontwheelmaterial', models.CharField(max_length=20)),
                ('rearwheelmaterial', models.CharField(max_length=20)),
                ('fronttyre', models.CharField(max_length=20)),
                ('reartyre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='specs',
            field=models.ManyToManyField(blank=True, related_name='bikes', to='bikes.Spec'),
        ),
    ]
